#!/usr/bin/env python3
"""Write the game's TLB-mapped code segments (.game, .debugger) as C arrays.

Rare's hand-written code reads lookup tables that sit inside its own code pages
(e.g. 0x150AA318) and the debugger reads data at 0x1600xxxx, so the host copies
these arrays to those addresses at startup (host/src/segments.cpp). The original
bytes come from the decomp's matching build (init/game/debugger.us.bin). Each
section's ROM address in the translator's layout comes from recomp_overlays.inl.

Words that prepare_elf.py changed for the translator (the prepared ELF differs
from the original there) are listed as rewrites, for mods that rebuild a hooked
function from its original instructions.

Idea from CBFD-Recompiled's emit_tlb_pages.py (MIT, Sean Ciaschi).

Usage: emit_segments.py <recomp dir> <out.c>
"""
import os
import re
import struct
import subprocess
import sys

SECTIONS = [(".init", "init.us.bin", None),
            (".game", "game.us.bin", "conker_game_segment"),
            (".debugger", "debugger.us.bin", "conker_debugger_segment")]


def elf_sections(elf):
    out = subprocess.run(["readelf", "-SW", elf], capture_output=True, text=True, check=True).stdout
    secs = {}
    for m in re.finditer(r"\]\s+(\.\S+)\s+PROGBITS\s+([0-9a-f]+)\s+([0-9a-f]+)\s+([0-9a-f]+)", out):
        secs[m.group(1)] = (int(m.group(2), 16), int(m.group(3), 16), int(m.group(4), 16))
    return secs


def main(d, out_path):
    elf = open(os.path.join(d, "conker.us.recomp.elf"), "rb").read()
    secs = elf_sections(os.path.join(d, "conker.us.recomp.elf"))
    inl = open(os.path.join(d, "out", "recomp_overlays.inl")).read()
    rom_of = {int(m.group(2), 16): int(m.group(1), 16)
              for m in re.finditer(r"\.rom_addr = (0x[0-9A-F]+), \.ram_addr = (0x[0-9A-F]+)", inl)}
    out = ["// Generated by tools/emit_segments.py. Do not edit.",
           "#include <stdint.h>", "#include <stddef.h>", ""]
    rewrites = []
    for name, binfile, sym in SECTIONS:
        vram, off, size = secs[name]
        orig = open(os.path.join(d, binfile), "rb").read()
        assert len(orig) == size, (name, len(orig), size)
        rom = rom_of[vram]
        prepared = elf[off:off + size]
        for i in range(0, size, 4):
            if orig[i:i + 4] != prepared[i:i + 4]:
                rewrites.append((rom + i, struct.unpack_from(">I", prepared, i)[0], name, vram + i))
        if sym is None:
            continue
        words = struct.unpack(f">{size // 4}I", orig)
        out += [f"const uint32_t {sym}_vram = 0x{vram:08X};",
                f"const uint32_t {sym}_rom = 0x{rom:08X};",
                f"const size_t {sym}_size = 0x{size:X};",
                f"const uint32_t {sym}[] = {{"]
        for k in range(0, len(words), 8):
            out.append("    " + ", ".join(f"0x{w:08X}" for w in words[k:k + 8]) + ",")
        out += ["};", ""]
    out.append("const uint32_t conker_code_rewrites[][2] = {")
    for rom, word, name, vram in rewrites:
        out.append(f"    {{ 0x{rom:08X}, 0x{word:08X} }}, // {name} 0x{vram:08X}")
    out += ["};", f"const size_t conker_code_rewrite_count = {len(rewrites)};", ""]
    open(out_path, "w", newline="\n").write("\n".join(out))
    print(f"{out_path}: {len(rewrites)} rewritten words")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(*sys.argv[1:])
